//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 -Wchłanianie witaminy B12 zachodzi w: (789 TRACZ) 
        ///ODP:E
        ///A. Dwunastnicy 
        ///B. Jelicie czczym 
        ///C. Żołądku 
        ///D. Jelicie grubym 
        ///E. Jelicie krętym 
        ///
        ///2 -Oczopląs optokinetyczny występuje u ludzi (132 TRACZ, 25 SKRYPT) 
        ///ODP:D
        ///A. Chorych z uszkodzeniem błędnika 
        ///B. Zdrowych po wykonaniu próby obrotowej i ma kierunek przeciwny do kierunku obrotów
        ///C. Chorych po wykonaniu próby obrotowej i ma kierunek zgodny z kierunkiem obrotów 
        ///D. Zdrowych podczas patrzenia na szybko przesuwające się obrazy 
        ///E. Choryc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fizjologia_Pytania_1_114 {
            get {
                return ResourceManager.GetString("Fizjologia_Pytania_1_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115 - Oddychanie Biota
        ///ODP:1
        ///A. W stanach śpiączki toksycznej, a także przy nadmiernym zwiększeniu ciśnienia śródczaszkowego, obserwuje się niekiedy inną formę oddychania periodycznego tzw. Oddychanie Biota. Polega ono na seriach 4-5 głębokich ruchów oddechowych o identycznejamplitudzie, rozdzielonych dużymi okresami bezdechu o bardzo nieregularnej długości. Oddychanie periodyczne-nieregularne przerwy w ruchach oddechowych występujące także w ciągu dnia. Charakteryzuje się nieregularnością rytmu, połączon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fizjologia_Pytania_115_294 {
            get {
                return ResourceManager.GetString("Fizjologia_Pytania_115_294", resourceCulture);
            }
        }
    }
}
